site_name: RoboTrail
theme:
    name: material
    custom_dirs: 'docs/overrides'
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.path
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    font:
        test: Roboto
        code: Roboto Mono
    palette:
        - scheme: default
          primary: blue
          accent: purple

extra_css:
    - 'extra.css'

plugins:
    - search

extra:
   social:
       - icon: fontawesome/brands/github-alt
         link: https://github.com/trushant05
       - icon: fontawesome/brands/twitter
         link: https://twitter.com/_trushant_
       - icon: fontawesome/brands/linkedin
         link: https://www.linkedin.com/in/trushant-adeshara

copyright: |
    &copy; 2024 <a href="https://github.com/trushant05" target="_blank" rel="noopener">Trushant Adeshara</a>
